name: "nexus-push"
version: "0.0.1"
usage: "Push chart or packaged chart to a specified repo"
description: |-
  Pushes a chart directory or packaged chart tgz to a specified repo,
  either by named repo or raw URL.  It also supports basic authenticated repos.
  See `helm nexus-push --help` for usage.
platformCommand:
  - os: linux
    arch: i386
    command: "$HELM_PLUGIN_DIR/push.sh"
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/push.sh"
  - os: windows
    arch: amd64
    command: "powershell $HELM_PLUGIN_DIR/push.ps1"
useTunnel: false
ignoreFlags: false
